{
  Throwable exception=null;
  try {
    return super.deleteIfExists(path);
  }
 catch (  Throwable t) {
    exception=t;
  }
 finally {
    sop("deleteIfExists: " + path(path),exception);
  }
  throw new AssertionError();
}
