{
  try {
    c.halfClose();
  }
 catch (  Exception e) {
    log.debug("exception on half close of: " + c,e);
  }
}
