{
  for (  Future<T> future : list) {
    try {
      func.apply(future.get());
    }
 catch (    ExecutionException e) {
      if (e.getCause() instanceof IOException)       throw (IOException)e.getCause();
      throw new RuntimeException(e.getCause());
    }
catch (    InterruptedException ie) {
      throw new ThreadInterruptedException(ie);
    }
  }
}
