{
  try {
    ignoreException(".");
    h.query(req);
    fail(failMessage);
  }
 catch (  SolrException e) {
    assertEquals(code.code,e.code());
    assertTrue("Unexpected error message. Expecting \"" + exceptionMessage + "\" but got \""+ e.getMessage()+ "\"",e.getMessage() != null && e.getMessage().contains(exceptionMessage));
  }
catch (  Exception e2) {
    throw new RuntimeException("Exception during query",e2);
  }
 finally {
    unIgnoreException(".");
  }
}
