{
  boolean exceptionCaught=false;
  try {
    handleRequestInternal(req,rsp,action);
    taskObject.setRspObject(rsp);
  }
 catch (  Exception e) {
    exceptionCaught=true;
    taskObject.setRspObjectFromException(e);
  }
 finally {
    removeTask("running",taskObject.taskId);
    if (exceptionCaught) {
      addTask("failed",taskObject,true);
    }
 else     addTask("completed",taskObject,true);
  }
}
