{
  if (TestTransactions.doFail && random().nextInt() % 10 <= 3) {
    if (VERBOSE) {
      System.out.println(Thread.currentThread().getName() + " TEST: now fail on purpose");
      new Throwable().printStackTrace(System.out);
    }
    throw new IOException("now failing randomly but on purpose");
  }
}
