{
  Throwable exception=null;
  try {
    super.deleteFile(path);
  }
 catch (  Throwable t) {
    exception=t;
  }
 finally {
    sop("deleteFile[SECURE]: " + path(path),exception);
  }
}
