{
  replicator.close();
  try {
    replicator.publish(createRevision(2));
    fail("should have failed on AlreadyClosedException");
  }
 catch (  AlreadyClosedException e) {
  }
}
