{
  maybeYield();
  maybeThrowDeterministicException();
  if (crashed) {
    throw new IOException("cannot rename after crash");
  }
  if (assertNoDeleteOpenFile && openFiles.containsKey(source)) {
    throw (AssertionError)fillOpenTrace(new AssertionError("MockDirectoryWrapper: file \"" + source + "\" is still open: cannot rename"),source,true);
  }
  boolean success=false;
  try {
    in.renameFile(source,dest);
    success=true;
  }
  finally {
    if (success) {
      if (unSyncedFiles.contains(source)) {
        unSyncedFiles.remove(source);
        unSyncedFiles.add(dest);
      }
      openFilesDeleted.remove(source);
    }
  }
}
