{
  try {
    this.task.run();
  }
 catch (  Exception e) {
    this.exception=e;
  }
}
