def errorExit(*messageParts):
    raise Exception(' '.join(messageParts))
